branches:
    only:
        - master
        - develop
    except:
        - /^v\d+\.\d+\.\d+$/

language: node_js
node_js:
    - v8
    - v7
    - v6
    - v5
    - v4

before_script:
  - npm install -g gulp
script: gulp

after_success:
  - npm run semantic-release

branches:
    except:
        - /^v\d+\.\d+\.\d+$/
