branches:
    except:
        - /^v\d+\.\d+\.\d+$/

language: node_js
node_js:
    - v8
    - v7
    - v6


script: npm test && npm run build:prod

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

after_success:
  - cat ./tests/coverage/lcov.info | ./node_modules/.bin/coveralls
  - npm run semantic-release

